/*
    FluxFox
    https://github.com/dbalsom/fluxfox

    Copyright 2024-2025 Daniel Balsom

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the “Software”),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in
    all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.

    --------------------------------------------------------------------------
*/

//! Byte -> Unicode mapping for ISO/IEC 8859-1 (Latin-1) character set.
//! Used by several platforms.
//! https://en.wikipedia.org/wiki/ISO/IEC_8859-1
//!

use crate::encoding::Chr;

pub const ISO_IEC_8859_1: [Chr; 256] = [
    Chr::C('\x00'),
    Chr::C('\x01'),
    Chr::C('\x02'),
    Chr::C('\x03'),
    Chr::C('\x04'),
    Chr::C('\x05'),
    Chr::C('\x06'),
    Chr::C('\x07'),
    Chr::C('\x08'),
    Chr::C('\x09'),
    Chr::C('\x0A'),
    Chr::C('\x0B'),
    Chr::C('\x0C'),
    Chr::C('\x0D'),
    Chr::C('\x0E'),
    Chr::C('\x0F'),
    Chr::C('\x10'),
    Chr::C('\x11'),
    Chr::C('\x12'),
    Chr::C('\x13'),
    Chr::C('\x14'),
    Chr::C('\x15'),
    Chr::C('\x16'),
    Chr::C('\x17'),
    Chr::C('\x18'),
    Chr::C('\x19'),
    Chr::C('\x1A'),
    Chr::C('\x1B'),
    Chr::C('\x1C'),
    Chr::C('\x1D'),
    Chr::C('\x1E'),
    Chr::C('\x1F'),
    Chr::P(' '),
    Chr::P('!'),
    Chr::P('"'),
    Chr::P('#'),
    Chr::P('$'),
    Chr::P('%'),
    Chr::P('&'),
    Chr::P('\''),
    Chr::P('('),
    Chr::P(')'),
    Chr::P('*'),
    Chr::P('+'),
    Chr::P(','),
    Chr::P('-'),
    Chr::P('.'),
    Chr::P('/'),
    Chr::P('0'),
    Chr::P('1'),
    Chr::P('2'),
    Chr::P('3'),
    Chr::P('4'),
    Chr::P('5'),
    Chr::P('6'),
    Chr::P('7'),
    Chr::P('8'),
    Chr::P('9'),
    Chr::P(':'),
    Chr::P(';'),
    Chr::P('<'),
    Chr::P('='),
    Chr::P('>'),
    Chr::P('?'),
    Chr::P('@'),
    Chr::P('A'),
    Chr::P('B'),
    Chr::P('C'),
    Chr::P('D'),
    Chr::P('E'),
    Chr::P('F'),
    Chr::P('G'),
    Chr::P('H'),
    Chr::P('I'),
    Chr::P('J'),
    Chr::P('K'),
    Chr::P('L'),
    Chr::P('M'),
    Chr::P('N'),
    Chr::P('O'),
    Chr::P('P'),
    Chr::P('Q'),
    Chr::P('R'),
    Chr::P('S'),
    Chr::P('T'),
    Chr::P('U'),
    Chr::P('V'),
    Chr::P('W'),
    Chr::P('X'),
    Chr::P('Y'),
    Chr::P('Z'),
    Chr::P('['),
    Chr::P('\\'),
    Chr::P(']'),
    Chr::P('^'),
    Chr::P('_'),
    Chr::P('`'),
    Chr::P('a'),
    Chr::P('b'),
    Chr::P('c'),
    Chr::P('d'),
    Chr::P('e'),
    Chr::P('f'),
    Chr::P('g'),
    Chr::P('h'),
    Chr::P('i'),
    Chr::P('j'),
    Chr::P('k'),
    Chr::P('l'),
    Chr::P('m'),
    Chr::P('n'),
    Chr::P('o'),
    Chr::P('p'),
    Chr::P('q'),
    Chr::P('r'),
    Chr::P('s'),
    Chr::P('t'),
    Chr::P('u'),
    Chr::P('v'),
    Chr::P('w'),
    Chr::P('x'),
    Chr::P('y'),
    Chr::P('z'),
    Chr::P('{'),
    Chr::P('|'),
    Chr::P('}'),
    Chr::P('~'),
    Chr::C('\x7F'),
    Chr::C('\u{0080}'),
    Chr::C('\u{0081}'),
    Chr::C('\u{0082}'),
    Chr::C('\u{0083}'),
    Chr::C('\u{0084}'),
    Chr::C('\u{0085}'),
    Chr::C('\u{0086}'),
    Chr::C('\u{0087}'),
    Chr::C('\u{0088}'),
    Chr::C('\u{0089}'),
    Chr::C('\u{008A}'),
    Chr::C('\u{008B}'),
    Chr::C('\u{008C}'),
    Chr::C('\u{008D}'),
    Chr::C('\u{008E}'),
    Chr::C('\u{008F}'),
    Chr::C('\u{0090}'),
    Chr::C('\u{0091}'),
    Chr::C('\u{0092}'),
    Chr::C('\u{0093}'),
    Chr::C('\u{0094}'),
    Chr::C('\u{0095}'),
    Chr::C('\u{0096}'),
    Chr::C('\u{0097}'),
    Chr::C('\u{0098}'),
    Chr::C('\u{0099}'),
    Chr::C('\u{009A}'),
    Chr::C('\u{009B}'),
    Chr::C('\u{009C}'),
    Chr::C('\u{009D}'),
    Chr::C('\u{009E}'),
    Chr::C('\u{009F}'),
    Chr::P('\u{00A0}'),
    Chr::P('\u{00A1}'),
    Chr::P('\u{00A2}'),
    Chr::P('\u{00A3}'),
    Chr::P('\u{00A4}'),
    Chr::P('\u{00A5}'),
    Chr::P('\u{00A6}'),
    Chr::P('\u{00A7}'),
    Chr::P('\u{00A8}'),
    Chr::P('\u{00A9}'),
    Chr::P('\u{00AA}'),
    Chr::P('\u{00AB}'),
    Chr::P('\u{00AC}'),
    Chr::P('\u{00AD}'),
    Chr::P('\u{00AE}'),
    Chr::P('\u{00AF}'),
    Chr::P('\u{00B0}'),
    Chr::P('\u{00B1}'),
    Chr::P('\u{00B2}'),
    Chr::P('\u{00B3}'),
    Chr::P('\u{00B4}'),
    Chr::P('\u{00B5}'),
    Chr::P('\u{00B6}'),
    Chr::P('\u{00B7}'),
    Chr::P('\u{00B8}'),
    Chr::P('\u{00B9}'),
    Chr::P('\u{00BA}'),
    Chr::P('\u{00BB}'),
    Chr::P('\u{00BC}'),
    Chr::P('\u{00BD}'),
    Chr::P('\u{00BE}'),
    Chr::P('\u{00BF}'),
    Chr::P('\u{00C0}'),
    Chr::P('\u{00C1}'),
    Chr::P('\u{00C2}'),
    Chr::P('\u{00C3}'),
    Chr::P('\u{00C4}'),
    Chr::P('\u{00C5}'),
    Chr::P('\u{00C6}'),
    Chr::P('\u{00C7}'),
    Chr::P('\u{00C8}'),
    Chr::P('\u{00C9}'),
    Chr::P('\u{00CA}'),
    Chr::P('\u{00CB}'),
    Chr::P('\u{00CC}'),
    Chr::P('\u{00CD}'),
    Chr::P('\u{00CE}'),
    Chr::P('\u{00CF}'),
    Chr::P('\u{00D0}'),
    Chr::P('\u{00D1}'),
    Chr::P('\u{00D2}'),
    Chr::P('\u{00D3}'),
    Chr::P('\u{00D4}'),
    Chr::P('\u{00D5}'),
    Chr::P('\u{00D6}'),
    Chr::P('\u{00D7}'),
    Chr::P('\u{00D8}'),
    Chr::P('\u{00D9}'),
    Chr::P('\u{00DA}'),
    Chr::P('\u{00DB}'),
    Chr::P('\u{00DC}'),
    Chr::P('\u{00DD}'),
    Chr::P('\u{00DE}'),
    Chr::P('\u{00DF}'),
    Chr::P('\u{00E0}'),
    Chr::P('\u{00E1}'),
    Chr::P('\u{00E2}'),
    Chr::P('\u{00E3}'),
    Chr::P('\u{00E4}'),
    Chr::P('\u{00E5}'),
    Chr::P('\u{00E6}'),
    Chr::P('\u{00E7}'),
    Chr::P('\u{00E8}'),
    Chr::P('\u{00E9}'),
    Chr::P('\u{00EA}'),
    Chr::P('\u{00EB}'),
    Chr::P('\u{00EC}'),
    Chr::P('\u{00ED}'),
    Chr::P('\u{00EE}'),
    Chr::P('\u{00EF}'),
    Chr::P('\u{00F0}'),
    Chr::P('\u{00F1}'),
    Chr::P('\u{00F2}'),
    Chr::P('\u{00F3}'),
    Chr::P('\u{00F4}'),
    Chr::P('\u{00F5}'),
    Chr::P('\u{00F6}'),
    Chr::P('\u{00F7}'),
    Chr::P('\u{00F8}'),
    Chr::P('\u{00F9}'),
    Chr::P('\u{00FA}'),
    Chr::P('\u{00FB}'),
    Chr::P('\u{00FC}'),
    Chr::P('\u{00FD}'),
    Chr::P('\u{00FE}'),
    Chr::P('\u{00FF}'),
];
