[package]
name = "fluxfox"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Balsom"]
readme = "README.md"
keywords = ["emulation", "ibm", "dos"]
repository = "https://github.com/dbalsom/fluxfox"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.14"
thiserror = "1.0"
logger = "0.4"
env_logger = "0.11"
regex = "1.5"
log = "0.4.22"

[workspace]
members = [
    "examples/imginfo",
]
