name: deploy_ff_egui_app.yml

on:
  push:
    branches:
      - pages_deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo binaries
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin
          restore-keys: ${{ runner.os }}-cargo-bin

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry
          restore-keys: ${{ runner.os }}-cargo-registry

      - name: Install Trunk
        run: cargo install trunk

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Install wasm-opt
        run: cargo install wasm-opt

      - name: Build ff_egui_app with Trunk
        working-directory: crates/ff_egui_app
        run: trunk build --release

      - name: Optimize WASM with wasm-opt
        working-directory: crates/ff_egui_app
        run: wasm-opt -Oz -o dist/ff_egui_app_bg.wasm dist/ff_egui_app_bg.wasm

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: crates/ff_egui_app/dist
